import { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { jobsApi, type Job } from '../../api/jobs';
import { applicationsApi, type Application } from '../../api/applications';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { Loader2, ExternalLink, Copy } from 'lucide-react';
import { Input } from '../../components/ui/Input';
import { CandidateCard } from '../../components/Recruiter/CandidateCard';
import { CandidateProfileDrawer } from '../../components/Recruiter/CandidateProfileDrawer';

const JobDetailPage = () => {
    const { jobId } = useParams<{ jobId: string }>();
    const [job, setJob] = useState<Job | null>(null);
    const [applications, setApplications] = useState<Application[]>([]);
    const [isLoading, setIsLoading] = useState(true);
    const [isLoadingApplications, setIsLoadingApplications] = useState(false);

    useEffect(() => {
        const fetchJob = async () => {
            if (!jobId) return;
            try {
                const data = await jobsApi.get(jobId);
                setJob(data);
            } catch (error) {
                console.error(error);
            } finally {
                setIsLoading(false);
            }
        };
        fetchJob();
    }, [jobId]);

    useEffect(() => {
        const fetchApplications = async () => {
            if (!jobId) return;
            setIsLoadingApplications(true);
            try {
                const data = await applicationsApi.getByJobId(jobId, {
                    sortBy: 'score',
                    sortOrder: 'desc'
                });
                // Ensure data is always an array
                setApplications(Array.isArray(data) ? data : []);
            } catch (error) {
                console.error('Failed to fetch applications:', error);
                setApplications([]); // Set empty array on error
            } finally {
                setIsLoadingApplications(false);
            }
        };
        if (jobId) {
            fetchApplications();
        }
    }, [jobId]);

    if (isLoading) return <div className="flex justify-center py-8"><Loader2 className="h-8 w-8 animate-spin" /></div>;
    if (!job) return <div className="text-center py-8">Job not found</div>;

    const publicLink = `${window.location.origin}/agent/${job.id}`;

    const [selectedCandidateId, setSelectedCandidateId] = useState<string | null>(null);

    const selectedCandidate = applications.find(app =>
        (app.id || app.applicationId) === selectedCandidateId
    );

    // Map selected candidate to the format expected by CandidateProfileDrawer if needed
    // Ideally CandidateProfileDrawer should handle the raw application object, which we implemented.

    return (
        <div className="space-y-6 animate-in fade-in duration-500">
            <div className="flex justify-between items-center">
                <div>
                    <h1 className="text-3xl font-bold">{job.role}</h1>
                    <p className="text-muted-foreground">{job.company_name} • {job.seniority}</p>
                </div>
                <div className="flex space-x-2">
                    <Button variant="outline" asChild>
                        <Link to={`/agent/${job.id}`} target="_blank">
                            <ExternalLink className="mr-2 h-4 w-4" />
                            View Public Page
                        </Link>
                    </Button>
                    <Button>Publish Job</Button>
                </div>
            </div>

            <div className="grid gap-6 md:grid-cols-3">
                <div className="md:col-span-2 space-y-6">
                    <Card>
                        <CardHeader>
                            <CardTitle>Enhanced Job Description</CardTitle>
                            <CardDescription>Generated by our AI agent based on your input.</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <div className="prose dark:prose-invert max-w-none whitespace-pre-wrap">
                                {job.enhanced_jd || job.raw_jd}
                            </div>
                        </CardContent>
                    </Card>

                    <Card>
                        <CardHeader>
                            <CardTitle>Candidate Matches</CardTitle>
                            <CardDescription>
                                {isLoadingApplications
                                    ? 'Loading applications...'
                                    : `${applications.length} ${applications.length === 1 ? 'match' : 'matches'} found`}
                            </CardDescription>
                        </CardHeader>
                        <CardContent>
                            {isLoadingApplications ? (
                                <div className="flex justify-center py-8">
                                    <Loader2 className="h-6 w-6 animate-spin" />
                                </div>
                            ) : !Array.isArray(applications) || applications.length === 0 ? (
                                <div className="text-center py-8 text-muted-foreground">
                                    <p>No applications found for this job yet.</p>
                                </div>
                            ) : (
                                <div className="space-y-4">
                                    {applications.map((application) => {
                                        const resumeScore = application.scores?.resumeScore;
                                        const unifiedScore = application.scores?.unifiedScore || application.alignmentScore;

                                        // Map Application to CandidateCard props
                                        const resume = application.parsedResume || application.candidate?.parsedResume;
                                        const experience = resume?.experience?.[0];
                                        const education = resume?.education?.[0];
                                        const contact = resume?.contact;

                                        const candidateData = {
                                            id: application.id || application.applicationId || '',
                                            name: application.candidateName,
                                            email: application.email,
                                            phone: application.phone,
                                            // Prefer parsed resume data, fallback to top-level fields
                                            role: experience?.title || application.candidate?.currentRole?.title,
                                            company: experience?.company || application.currentCompany || application.candidate?.currentRole?.company,
                                            location: experience?.location || application.candidate?.currentRole?.location,
                                            education: education ? `${education.degree} ${education.field ? `, ${education.field}` : ''} at ${education.institution}` :
                                                (application.candidate?.education ? `${application.candidate.education.degree || ''} ${application.candidate.education.field || ''} at ${application.candidate.education.university || ''}` : undefined),
                                            bio: application.resumePreview || application.candidate?.bio || application.candidate?.summary,
                                            skills: application.tags || application.candidate?.tags || application.candidate?.skills,
                                            matchScore: unifiedScore,
                                            resumeScore: resumeScore,
                                            status: typeof application.status === 'string' ? application.status : 'Unknown',
                                            socialLinks: {
                                                linkedin: contact?.linkedin || application.candidate?.linkedin,
                                                github: contact?.github || application.candidate?.github,
                                                portfolio: contact?.portfolio || application.candidate?.portfolio || application.candidate?.website
                                            }
                                        };

                                        return (
                                            <CandidateCard
                                                key={candidateData.id}
                                                candidate={candidateData}
                                                onShortlist={(id) => console.log('Shortlist', id)}
                                                onView={(id) => setSelectedCandidateId(id)}
                                            />
                                        );
                                    })}
                                </div>
                            )}
                        </CardContent>
                    </Card>
                </div>

                <div className="space-y-6">
                    <Card>
                        <CardHeader>
                            <CardTitle>Job Settings</CardTitle>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <div className="space-y-2">
                                <label className="text-sm font-medium">Public Link</label>
                                <div className="flex space-x-2">
                                    <Input readOnly value={publicLink} />
                                    <Button variant="ghost" size="icon" onClick={() => navigator.clipboard.writeText(publicLink)}>
                                        <Copy className="h-4 w-4" />
                                    </Button>
                                </div>
                            </div>
                            <div className="space-y-2">
                                <label className="text-sm font-medium">Status</label>
                                <div className="inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 border-transparent bg-secondary text-secondary-foreground hover:bg-secondary/80">
                                    {job.status}
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                </div>
            </div>

            <CandidateProfileDrawer
                isOpen={!!selectedCandidateId}
                onClose={() => setSelectedCandidateId(null)}
                candidate={selectedCandidate}
            />
        </div>
    );
};

export default JobDetailPage;
